<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>066bbaaa-e795-4eda-8270-a4a9a85fb291</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Liotecnica.PortalAuth.Application\Liotecnica.PortalAuth.Application.csproj" />
    <ProjectReference Include="..\Liotecnica.BuildingBlocks.Api\Liotecnica.BuildingBlocks.Api.csproj" />
    <ProjectReference Include="..\Liotecnica.BuildingBlocks.Logging\Liotecnica.BuildingBlocks.Logging.csproj" />
    <ProjectReference Include="..\Liotecnica.BuildingBlocks.Observability\Liotecnica.BuildingBlocks.Observability.csproj" />
    <ProjectReference Include="..\Liotecnica.BuildingBlocks.Web\Liotecnica.BuildingBlocks.Web.csproj" />
    <ProjectReference Include="..\Liotecnica.PortalAuth.Infrastructure\Liotecnica.PortalAuth.Infrastructure.csproj" />
  </ItemGroup>

</Project>
